name: "Feedback op Preventieportal"
description: "Meld een fout, kapotte link, inhoudelijke verbetering of idee."
title: "[Feedback]: "
labels: ["feedback"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Dank voor je feedback! 👋 Vul de velden hieronder zo volledig mogelijk in.  
        _Deze issue-template hoort bij de trainingsportal._

  - type: input
    id: pagina
    attributes:
      label: "Pagina / onderdeel"
      description: "Welke pagina of sectie? (bijv. docs/firepagina.html of 'Header index')"
      placeholder: "bijv. docs/contact.html"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: "Type feedback"
      description: "Kies wat het beste past."
      options:
        - "Bug (technisch)"
        - "Tekst/inhoud"
        - "Toegankelijkheid"
        - "Link kapot"
        - "Idee/verbetering"
    validations:
      required: true

  - type: dropdown
    id: prioriteit
    attributes:
      label: "Prioriteit"
      options:
        - "Laag"
        - "Normaal"
        - "Hoog"
    validations:
      required: true

  - type: textarea
    id: beschrijving
    attributes:
      label: "Korte beschrijving"
      description: "Wat is het probleem of voorstel in één alinea?"
      placeholder: "Beschrijf kort wat er mis is of wat beter kan."
    validations:
      required: true

  - type: textarea
    id: stappen
    attributes:
      label: "Stappen om te reproduceren (voor bugs)"
      description: "Hoe konden we het probleem reproduceren?"
      placeholder: |
        1. Ga naar ...
        2. Klik op ...
        3. Zie foutmelding ...
      render: bash
